2015/10/03 06:17:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/
---
2015/10/03 06:36:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller_auto/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php?r=gii/default/index
---
2015/10/03 06:37:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii-1.1.16.bca042\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii-1.1.16.bca042\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii-1.1.16.bca042\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii-1.1.16.bca042\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/taller_auto/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php?r=gii/default/index
---
2015/10/03 14:48:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/index.php?r=mecanico/index
HTTP_REFERER=http://localhost/tallermecanica/
---
2015/10/14 06:06:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php
---
2015/10/14 06:07:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php
---
2015/10/14 06:07:31 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php
---
2015/10/14 06:20:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php?r=site/index
---
2015/10/14 06:20:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\taller_auto\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\taller_auto\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\taller_auto\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\taller_auto\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\taller_auto\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\taller_auto\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\taller_auto\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\taller_auto\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\taller_auto\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\taller_auto\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\taller_auto\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\taller_auto\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\taller_auto\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\taller_auto\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\taller_auto\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\taller_auto\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\taller_auto\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\taller_auto\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php?r=site/index
---
2015/10/15 01:25:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\taller_auto\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\taller_auto\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/taller_auto/index.php?r=mecanico/index
HTTP_REFERER=http://localhost:8085/taller_auto/index.php
---
2015/10/15 01:37:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:37:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:38:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:38:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:38:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:39:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff2".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff2?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.woff".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.woff?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 01:40:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "fonts/fontawesome-webfont.ttf".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('fonts/fontaweso...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/fonts/fontawesome-webfont.ttf?v=4.4.0
HTTP_REFERER=http://localhost:8085/taller_auto/css/fonts.css
---
2015/10/15 02:14:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "sevicio/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('sevicio/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/taller_auto/sevicio/index.html
---
<<<<<<< HEAD
2015/10/17 17:45:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/
---
2015/10/17 17:46:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/
---
2015/10/17 17:50:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/index.html
---
2015/10/21 22:08:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/
---
2015/10/22 21:15:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/
=======
2015/10/22 02:41:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
---
2015/10/22 02:41:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "js".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('js')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('js')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/js/mecanic...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\taller_auto\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/taller_auto/site/js/mecanico.js
HTTP_REFERER=http://localhost:8085/taller_auto/site/index.html
>>>>>>> 886bff13a2e8b7e45dff0fbff96aeaba109ea287
---
2015/10/22 21:22:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(22): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/contact.html
---
2015/10/22 21:23:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(22): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/contact.html
---
2015/10/22 21:23:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(22): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
---
2015/10/22 21:23:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(458): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(670): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#12 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\tallermecanica\protected\views\mecanico\index.php(22): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#17 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#18 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#19 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\tallermecanica\protected\controllers\MecanicoController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): MecanicoController->actionIndex()
#22 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#31 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#32 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#33 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/contact.html
---
2015/10/28 12:44:25 [error] [php] Undefined variable: dataProvider (C:\xampp\htdocs\tallermecanica\protected\views\site\index.php:11)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\tallermecanica\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\tallermecanica\index.php(13): CWebApplication->run()
REQUEST_URI=/tallermecanica/site/index.html
in C:\xampp\htdocs\tallermecanica\protected\views\site\index.php (11)
in C:\xampp\htdocs\tallermecanica\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 13:24:28 [error] [php] Undefined variable: dataProvider (C:\xampp\htdocs\tallermecanica\protected\views\site\index.php:11)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\tallermecanica\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\tallermecanica\index.php(13): CWebApplication->run()
REQUEST_URI=/tallermecanica/site/index.html
in C:\xampp\htdocs\tallermecanica\protected\views\site\index.php (11)
in C:\xampp\htdocs\tallermecanica\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:06:32 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'taller_mec.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:07:59 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'taller_mec.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:08:34 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'taller_mec.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:10:02 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'taller_mec.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:10:42 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'taller_mec.listaservicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `listaservicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:10:45 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'taller_mec.listaservicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `listaservicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:30:50 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:30:53 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:31:12 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:31:15 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:31:23 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:31:25 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:31:39 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:31:40 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:32:16 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:32:18 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:32:31 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:32:33 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:32:57 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:32:59 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.lista_servicios' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `mydb`.`lista_servicios`.
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 14:55:02 [error] [exception.CException] exception 'CException' with message 'Property "Servicio.costo_total" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('costo_total')
#1 C:\xampp\htdocs\tallermecanica\protected\views\servicio\_view.php(21): CActiveRecord->__get('costo_total')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{sort...')
#8 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\tallermecanica\protected\views\servicio\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(128): CController->render('index', Array)
#16 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#26 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('servicio/index')
#27 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#28 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/tallermecanica/servicio/index.html
HTTP_REFERER=http://localhost/tallermecanica/servicio/index.html
---
2015/10/28 15:18:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mecanico/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/index.html
---
2015/10/28 16:35:56 [error] [php] Trying to get property of non-object (C:\xampp\htdocs\tallermecanica\protected\views\servicio\_view.php:23)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(291): ServicioController->renderFile()
#1 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#2 unknown(0): CListView->renderSection()
#3 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback()
#4 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(149): CListView->renderContent()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(181): CListView->run()
#6 C:\xampp\htdocs\tallermecanica\protected\views\servicio\index.php(20): ServicioController->widget()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): ServicioController->renderInternal()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(869): ServicioController->renderFile()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(782): ServicioController->renderPartial()
#11 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(128): ServicioController->render()
#12 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#14 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ServicioController->runAction()
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#17 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ServicioController->filterAccessControl()
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#19 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#20 C:\xampp\htdocs\yii\framework\web\CController.php(265): ServicioController->runActionWithFilters()
#21 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ServicioController->run()
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#23 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\tallermecanica\index.php(13): CWebApplication->run()
REQUEST_URI=/tallermecanica/servicio/index.html
in C:\xampp\htdocs\tallermecanica\protected\views\servicio\_view.php (23)
in C:\xampp\htdocs\tallermecanica\protected\views\servicio\index.php (20)
in C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php (128)
2015/10/28 17:48:03 [error] [exception.CException] exception 'CException' with message 'Property "Servicio.placaVehiculo" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('placaVehiculo')
#1 C:\xampp\htdocs\tallermecanica\protected\views\servicio\_view.php(13): CActiveRecord->__get('placaVehiculo')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(130): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, false)
#4 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\\xampp\\htdocs...', Array)
#5 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback('/{(\\w+)}/', Array, '{summary}\n{sort...')
#8 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(149): CBaseListView->renderContent()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(181): CBaseListView->run()
#10 C:\xampp\htdocs\tallermecanica\protected\views\servicio\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#12 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(128): CController->render('index', Array)
#16 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#26 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('servicio/index')
#27 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#28 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/tallermecanica/servicio/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/index.html
---
2015/10/28 18:01:19 [error] [php] Undefined variable: criteria (C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php:125)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): ServicioController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): ServicioController->filterAccessControl()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): ServicioController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ServicioController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\tallermecanica\index.php(13): CWebApplication->run()
REQUEST_URI=/tallermecanica/servicio/index.html
in C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php (125)
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 18:07:35 [error] [exception.CException] exception 'CException' with message 'Property "CActiveDataProvider.0" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(96): CComponent->__set('0', 'criteria')
#1 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(130): CActiveDataProvider->__construct('Servicio', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('servicio/index')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/tallermecanica/servicio/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/index.html
---
2015/10/28 18:08:09 [error] [exception.CException] exception 'CException' with message 'Property "CActiveDataProvider.0" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(96): CComponent->__set('0', 'criteria')
#1 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(130): CActiveDataProvider->__construct('Servicio', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('servicio/index')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/tallermecanica/servicio/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/index.html
---
2015/10/28 18:08:36 [error] [exception.CException] exception 'CException' with message 'Property "CActiveDataProvider.0" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(96): CComponent->__set('0', 'criteria')
#1 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(129): CActiveDataProvider->__construct('Servicio', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('servicio/index')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/tallermecanica/servicio/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/index.html
---
2015/10/28 18:08:45 [error] [exception.CException] exception 'CException' with message 'Property "CActiveDataProvider.0" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(96): CComponent->__set('0', 'criteria')
#1 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(129): CActiveDataProvider->__construct('Servicio', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('servicio/index')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/tallermecanica/servicio/index.html
HTTP_REFERER=http://localhost/tallermecanica/site/index.html
---
2015/10/28 18:08:47 [error] [exception.CException] exception 'CException' with message 'Property "CActiveDataProvider.0" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(96): CComponent->__set('0', 'criteria')
#1 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(129): CActiveDataProvider->__construct('Servicio', Array)
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('servicio/index')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/tallermecanica/servicio/index.html
---
2015/10/28 18:10:25 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'servicio.fecha' in 'order clause'. The SQL statement executed was: SELECT * FROM `servicio` `t` ORDER BY servicio.fecha desc LIMIT 10.
in C:\xampp\htdocs\tallermecanica\protected\views\servicio\index.php (20)
in C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php (133)
in C:\xampp\htdocs\tallermecanica\index.php (13)
2015/10/28 18:10:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'servicio.fecha' in 'order clause'. The SQL statement executed was: SELECT * FROM `servicio` `t` ORDER BY servicio.fecha desc LIMIT 10' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1356): CDbCommand->queryAll()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1475): CActiveRecord->query(Object(CDbCriteria), true)
#3 C:\xampp\htdocs\yii\framework\web\CActiveDataProvider.php(199): CActiveRecord->findAll(Object(CDbCriteria))
#4 C:\xampp\htdocs\yii\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#5 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(125): CDataProvider->getData()
#6 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#7 C:\xampp\htdocs\yii\framework\web\CBaseController.php(147): CListView->init()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.CLi...', Array)
#9 C:\xampp\htdocs\tallermecanica\protected\views\servicio\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#10 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#14 C:\xampp\htdocs\tallermecanica\protected\controllers\ServicioController.php(133): CController->render('index', Array)
#15 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ServicioController->actionIndex()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#21 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#25 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('servicio/index')
#26 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#27 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/tallermecanica/servicio/index.html
---
2015/10/28 18:23:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mecanico/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/servicio/index.html
---
2015/10/29 00:25:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mecanico/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/servicio/index.html
---
2015/10/29 00:27:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mecanico/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/servicio/index.html
---
2015/10/29 00:28:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mecanico/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/servicio/index.html
---
2015/10/29 00:28:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mecanico/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/mecanico/index.html
---
2015/10/29 00:35:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mecanico/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/servicio/index.html
---
2015/10/29 00:35:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "mecanico/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('mecanico/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\tallermecanica\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/tallermecanica/mecanico/index.html
HTTP_REFERER=http://localhost/tallermecanica/servicio/index.html
---
